repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: isort
        name: isort
        always_run: true
        entry: isort .
        language: system
        types: [python]

      - id: black
        name: black
        always_run: true
        entry: black .
        language: system
        types: [python]

      - id: flake8
        name: flake8
        always_run: true
        entry: flake8
        language: python
        types: [python]

      - id: pytest
        name: pytest
        always_run: true
        pass_filenames: false
        entry: pytest --ignore=./tests/integration
        language: system
